---
name: ⬆️ Update

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare
        run: |
          npm -v
          npm i -g pnpm
      - name: Update
        run: pnpm update
      - name: Build
        run: npm run build
      - name: Update Hero Picture
        run: |
          git clone https://github.com/CofficLab/JuiceEditor
          cp -f JuiceEditor/docs/hero.png ./docs/hero.png
          rm -rf JuiceEditor
      - name: Commit
        id: commit
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add -A
          if git diff --staged --quiet; then
            echo "No changes to commit"
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            git commit -m "👷 CI: Update Package"
            git push origin main
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
      - name: Check if changed
        if: steps.commit.outputs.changed == 'true'
        run: |
          echo "Changes were made and committed"
